### ISSUE TITLE
python 2/3 compatibility

### ISSUE THREAD

**Issue by heilgeirr** [jdi-testing/jdi-python#3]
At the moment JDI-python runs only under python3. Imho, we also need support for python 2.7, because there are lot of projects still using python2.

Brief introduction to the topic - https://docs.python.org/3/howto/pyporting.html

Changes required are mostly subtle (package level __init__.py files are required for python2, additional packages dependencies exist for python2, there are some minor differences for selenium implementation between py2 and py3)

**Comment by zhidelev** [comment]
Python 2 updates stop from April 2020 
https://www.python.org/downloads/release/python-2718/
