### ISSUE TITLE
Can be used only on windows platform

### ISSUE THREAD

**Issue by pnatashap** [jdi-testing/jdi-python#34]
There is a dependency on pywin32, so can't be used on Linux based OS

**Comment by zhidelev** [comment]
Yes, @pnatashap , you are right. It's used for keys input for different input fields. I am not good at JDI, so I am not sure is it a feature that should be supported on different platforms or it's possible just to remove it. For this moment it was left as it is =)

**Comment by pnatashap** [comment]
Fixed in #69
