### ISSUE TITLE
Remove __future__ usage

### ISSUE THREAD

**Issue by zhidelev** [jdi-testing/jdi-python#45]
Some modules have old ```__future__``` for Python 2 compatibility. Now Python 3 is supported only so ```__future__``` could be eliminated.

**Comment by yumalkhasyan** [comment]
So maybe we should remove [python 2/3 compatibility](https://github.com/jdi-testing/jdi-python/issues/3) task?

**Comment by zhidelev** [comment]
@yumalkhasyan good point, I have closed that one 👍
